install: make
language: cpp
compiler: gcc
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
   - MATRIX_EVAL="CC=gcc-4.8 && CXX=g++-4.8"

scripts: 
    - ./build.sh
